#Display name
servername: "Singularity Server!"

#Message of the day
motd: "I am a Server!"

#The port the http and socket server will use
port: 5000

#A bucket is like a chunk in minecraft
bucket:
  width: 16
  height: 16

#How many ticks per second should happen
tickRate: 60

#Use the http API?
enableAPI: true

#Some things with the player
player:
  #The speed in tiles per second the player can walk
  walkSpeed: 1.5
  #The speed of the items, the player is throwing
  throwSpeed: 2.3
  #Is the player allowed to have a 0 character name?
  allowEmptyName: true

#A server can host multiple rounds at the same time
games:
  - name: "Default Game"
    maps:
    - "lab/lab"
    - "lab/lift"
    - "lab/end"
    playerLimit: 20
    gamemode: "gmSingularity"
    gamemodeConfig:
      elevatorTime: 30
      elevatorDepartTime: 30
      elevatorEscapeTime: 30
      readyPercentage: 51
      world1LiftX: 43
      world1LiftY: 34
      world2LiftX: 18
      world2LiftY: 18
      world3LiftX: 17
      world3LiftY: 12
      liftWidth: 5
      liftHeight: 4
      singularityX: 26
      singularityY: 10