#Display name
servername: "Offical Test Server!"

#Message of the day
motd: "This is a test server!"

#The port the http and socket server will use
port: 5000

#A bucket is like a chunk in minecraft
bucket:
  width: 16
  height: 16

#How many ticks per second should happen
tickRate: 30

#Use the http API?
enableAPI: true

#Some things with the player
player:
  #The speed in tiles per second the player can walk
  walkSpeed: 1.5
  #Is the player allowed to have a 0 character name?
  allowEmptyName: true
#Use the atomspherics simulation system?
enableAtmos: true

#A server can host multiple rounds at the same time
games:
  - gamemode: "gmSingularity"
    maps:
    - "lab"
    playerLimit: 20
#A second game would look like this:
#  - gamemode: "gmSingularity"
#    maps:
#    - "lab"